name: Run Gradle test

on:
  push:
    branches:
      - master
      - releases/*

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: burrunan/gradle-cache-action@v1
      name: gradle build
      with:
        arguments: build validatePlugins
        save-gradle-dependencies-cache: true
    - uses: burrunan/gradle-cache-action@v1
      name: publish plugin to portal
      with:
        arguments: publishPlugins --dry-run
        execution-only-caches: true
        properties: |
          gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
          gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}