name: Run Gradle on PRs

on: pull_request

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-java@v1
      with:
        java-version: 8
    - uses: burrunan/gradle-cache-action@v1
      name: gradle build
      with:
        arguments: build
    - uses: actions/upload-artifact@v2.2.3
      with:
        name: Package
        path: build/libs