name: Run Gradle test

on:
  push:
    branches:
      - master
      - releases/*

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-java@v2.5.0
      with:
        distribution: 'temurin'
        java-version: '8'
    - uses: gradle/gradle-build-action@v2
    - name: gradle build and validate plugin
      run:  ./gradlew build validatePlugins
