on:
  push:
    tags:
    - 'v*'

name: Make github release and publish to p.g.o

jobs:
  build:
    name: Make github release and publish to p.g.o
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.0
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
    - name: validate plugin
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: validatePlugins
        save-gradle-dependencies-cache: true
    - uses: burrunan/gradle-cache-action@v1
      name: publish plugin to portal
      with:
        arguments: publishPlugins
        save-gradle-dependencies-cache: true
        properties: |
          gradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }}
          gradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
    - name: Create Github Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release v${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false